module.exports = {
  // eslint-plugin-react
  // https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
  'react/boolean-prop-naming': 0,
  'react/button-has-type': 1,
  'react/default-props-match-prop-types': 1,
  'react/destructuring-assignment': [1, 'always', { 'ignoreClassFields': true }],
  'react/display-name': 0,
  'react/forbid-component-props': 0,
  'react/forbid-dom-props': 0,
  'react/forbid-foreign-prop-types': 0,
  'react/function-component-definition': [1, {
    namedComponents: 'arrow-function',
    unnamedComponents: 'arrow-function'
  }],
  'react/jsx-boolean-value': [1, 'always'],
  'react/jsx-child-element-spacing': 2,
  'react/jsx-closing-bracket-location': [1, 'after-props'],
  'react/jsx-closing-tag-location': 1,
  'react/jsx-curly-brace-presence': [1, { props: 'never', children: 'never' }],
  'react/jsx-curly-newline': [1, 'never'],
  'react/jsx-curly-spacing': [
    1,
    {
      when: 'always',
      children: true,
      allowMultiline: true,
      spacing: { objectLiterals: 'never' },
    },
  ],
  'react/jsx-equals-spacing': [1, 'never'],
  'react/jsx-filename-extension': [1, { extensions: ['.jsx', '.tsx'] }],
  'react/jsx-first-prop-new-line': [1, 'multiline-multiprop'],
  'react/jsx-fragments': [1, 'syntax'],
  'react/jsx-handler-names': 1,
  'react/jsx-indent-props': [1, 2],
  'react/jsx-indent': [1, 2],
  'react/jsx-key': 1,
  'react/jsx-max-depth': [1, { max: 5 }],
  'react/jsx-max-props-per-line': [2, { maximum: 4, when: 'always' }],
  'react/jsx-no-bind': 0,
  'react/jsx-no-comment-textnodes': 1,
  'react/jsx-no-duplicate-props': 1,
  'react/jsx-no-literals': 0,
  'react/jsx-no-script-url': 2,
  'react/jsx-no-target-blank': [2, { enforceDynamicLinks: 'always' }],
  'react/jsx-no-undef': 1,
  'react/jsx-no-useless-fragment': 1,
  'react/jsx-one-expression-per-line': 0,
  'react/jsx-pascal-case': 1,
  'react/jsx-props-no-multi-spaces': 1,
  'react/jsx-props-no-spreading': 0,
  'react/jsx-sort-default-props': 0,
  'react/jsx-sort-props': 0,
  'react/jsx-tag-spacing': [
    1,
    {
      closingSlash: 'never',
      beforeSelfClosing: 'always',
      afterOpening: 'never',
      beforeClosing: 'never',
    },
  ],
  'react/jsx-uses-react': 1,
  'react/jsx-uses-vars': 1,
  'react/jsx-wrap-multilines': [1, { return: 'parens-new-line', arrow: 'parens-new-line' }],
  'react/no-access-state-in-setstate': 2,
  'react/no-array-index-key': 1,
  'react/no-children-prop': 1,
  'react/no-danger-with-children': 2,
  'react/no-danger': 2,
  'react/no-deprecated': 1,
  'react/no-did-mount-set-state': 2,
  'react/no-did-update-set-state': 2,
  'react/no-direct-mutation-state': 2,
  'react/no-find-dom-node': 2,
  'react/no-is-mounted': 2,
  'react/no-multi-comp': 2,
  'react/no-redundant-should-component-update': 1,
  'react/no-render-return-value': 1,
  'react/no-set-state': 0,
  'react/no-string-refs': 1,
  'react/no-this-in-sfc': 2,
  'react/no-typos': 1,
  'react/no-unescaped-entities': 1,
  'react/no-unknown-property': 1,
  'react/no-unsafe': 1,
  'react/no-unused-prop-types': 1,
  'react/no-unused-state': 1,
  'react/no-will-update-set-state': 2,
  'react/prefer-es6-class': 1,
  'react/prefer-read-only-props': 0,
  'react/prefer-stateless-function': 1,
  'react/prop-types': 0,
  'react/react-in-jsx-scope': 1,
  'react/require-default-props': 1,
  'react/require-optimization': 1,
  'react/require-render-return': 2,
  'react/self-closing-comp': 1,
  'react/sort-comp': 0,
  'react/sort-prop-types': 0,
  'react/state-in-constructor': 0,
  'react/static-property-placement': 0,
  'react/style-prop-object': 2,
  'react/void-dom-elements-no-children': 2,

  // eslint-plugin-react-hooks
  'react-hooks/rules-of-hooks': 2,
  'react-hooks/exhaustive-deps': 1,
};
